### ISSUE TITLE
this._calculateScanRegion is not a function

### ISSUE THREAD

**Issue by Lionberg** [nimiq/qr-scanner#181]
Documentation says I can use option **calculateScanRegion**

But when I initialize an object with this option, I get error.

```
window.lubenreader_scanner = new QrScanner(window.lubenreader_videoFrameElement, 
    function(result){
        window.lubenreader_setResult(result);
    },
    {highlightScanRegion: true,
    highlightCodeOutline: true,
    calculateScanRegion: {width: 200, height: 200 }});
```

this._calculateScanRegion is not a function

**Comment by 03juan** [comment]
The [typespec](https://github.com/nimiq/qr-scanner/blob/1cd3b15285a21662cb6057c7cf06fe412b00fe65/types/qr-scanner.d.ts#L30) defines this parameter as a function that receives the `HTMLVideoElement` and expects you to return a `ScanRegion`.

```javascript
calculateScanRegion?: (video: HTMLVideoElement) => QrScanner.ScanRegion;
```

Your code should at minimum change to:

```javascript
calculateScanRegion: () => { return { width: 200, height: 200 } }
```

**Comment by Ruxx28** [comment]
How do I get it to update to the right position in the middle of the screen?

**Comment by jewelsonn** [comment]
> How do I get it to update to the right position in the middle of the screen?


This was the test code I used in my vue 3  
**Pass in this option to the scanner instance**
```javascript
calculateScanRegion: () => {
          return {
            x: (calculateScanRegion(scannerVideo.value).x),
            y: (calculateScanRegion(scannerVideo.value).y),
            width: (calculateScanRegion(scannerVideo.value).width),
            height: (calculateScanRegion(scannerVideo.value).height)
          }
        }
```
**Calculate the region x and y and size to center it**
```javascript
const calculateScanRegion = (video) => {
  const videoWidth = video.videoWidth;
  const videoHeight = video.videoHeight;
  const size = Math.min(videoWidth, videoHeight) * 0.67; // Adjust the factor as needed
  const x = (videoWidth - size) / 2;
  const y = (videoHeight - size) / 2;

  return { x, y, width: size, height: size };
};
```
**This is the css code for the `<div id="video-container>` which has a `<video id="camera-sensor">`  element as child with the** 
```css
#video-container {
  line-height: 0;
  position: absolute;
  width: inherit !important;
  height: inherit !important;
  overflow: hidden;
}

#camera--sensor {
  display: flex;
  align-items: center;
  justify-content: center;
  justify-items: center;
  margin-left: auto;
  margin-right: auto;
  padding: auto;
  height: inherit;
  width: inherit;
  object-fit: cover;
  overflow: hidden;
}
```
